#!/usr/bin/env bash

# Central version pins for installer scripts.
# Update values here when tool requirements change.

NEOVIM_REQUIRED_VERSION="0.11.0"
NEOVIM_FALLBACK_VERSION="0.11.0"

# Placeholders for future version-gated tooling.
BUILD_ESSENTIAL_REQUIRED_VERSION=""
CURL_REQUIRED_VERSION=""
FD_REQUIRED_VERSION=""
FZF_REQUIRED_VERSION=""
GIT_REQUIRED_VERSION=""
PYTHON_REQUIRED_VERSION=""
PYTHON_VENV_REQUIRED_VERSION=""
RIPGREP_REQUIRED_VERSION=""
UNZIP_REQUIRED_VERSION=""
WL_CLIPBOARD_REQUIRED_VERSION=""
XCLIP_REQUIRED_VERSION=""
XSEL_REQUIRED_VERSION=""
JETBRAINS_MONO_REQUIRED_VERSION=""
